# Generated by Django 6.0.4 on 2026-08-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_room_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
